allprojects {
    apply plugin: 'java'
    group = 'sushi'
    version = '0.3.0-SNAPSHOT'
    description = 'SUSHI'

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation 'junit:junit:4.13.2'
    }
    
    ext {
    	javaVersion = JavaLanguageVersion.of(8)
    }
    
    java {
    	toolchain {
    		languageVersion = javaVersion
    	}
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
